version: '3.8'

secrets:
  db_password:
    file: ./.secrets/db_password.txt
  cf_access_key:
    file: ./.secrets/cf_access_key.txt
  cf_secret_key:
    file: ./.secrets/cf_secret_key.txt
services:
  db:
    image: postgres:15
    container_name: chess_db_production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net
    secrets:
      - db_password
    

  backend:
    build: ./backend
    container_name: chess_backend_production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORTS=5062
      - ConnectionStrings__Host=db
      - ConnectionStrings__Database=${POSTGRES_DB}
      - ConnectionStrings__Username=${POSTGRES_USER}
      - Storage__Provider=R2
      - Storage__AccountId=${CF_ACCOUNT_ID}
      - Storage__BucketName=${CF_BUCKET_NAME}
      - Storage__PublicBaseUrl=${CF_PUBLIC_URL}
    depends_on:
      db :
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - frontend-net
    secrets:
      - db_password
      - cf_access_key
      - cf_secret_key
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5062/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    
   
  frontend:
    build: ./frontend
    container_name: chess_frontend_production
    working_dir: /app
    ports:
      - "443:443"
    volumes:
      - ./chess.site.pem:/etc/ssl/cert.pem:ro
      - ./chess.site-key.pem:/etc/ssl/key.pem:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - frontend-net
  
  redis:
    image: redis:7-alpine
    container_name: chess_redis_production
    volumes:
      - redis_data_production:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data_production:
  postgres_data_production:
  data_protection_keys:
networks:
  frontend-net:
  backend-net:

