version: '3.8'

secrets:
  db_password:
    file: ./.secrets/db_password.txt
  
services:
  db:
    image: postgres:15
    container_name: chess_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    secrets:
      - db_password
  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: chess_backend
    working_dir: /app
    ports:
      - "5062:5062"
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
      - dotnet_packages:/root/.nuget/packages
        - ./backend/wwwroot/uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5062
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - Storage__Provider=Local
      - ConnectionStrings__Host=db
      - ConnectionStrings__Database=${POSTGRES_DB}
      - ConnectionStrings__Username=${POSTGRES_USER}
    secrets:
      - db_password
    command: >
      sh -c "
      dotnet restore &&
      dotnet watch run --no-launch-profile
      "
    depends_on:
      - db
      - redis
    networks:
      - backend-net
      - frontend-net

  frontend:
    image: node:20-alpine
    container_name: chess_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - backend
    networks:
      - frontend-net

  redis:
    image: redis:7-alpine
    container_name: chess_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend-net

volumes:
  redis_data:
  postgres_data:
  dotnet_packages:
  frontend_node_modules:
networks:
  frontend-net:
  backend-net:
    
