version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chess_db_production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: chess_backend_production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5062
      - ConnectionStrings__Default=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis
    restart: unless-stopped
   
  frontend:
    build: ./frontend
    container_name: chess_frontend_production
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: chess_redis_production
    volumes:
      - redis_data_production:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data_production:
  postgres_data_production:
