

secrets:
  db_password:
    file: ./.secrets/db_password.txt
  cf_access_key:
    file: ./.secrets/cf_access_key.txt
  cf_secret_key:
    file: ./.secrets/cf_secret_key.txt
services:
  db:
    image: postgres:15
    container_name: chess_db_production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_production:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-net
    secrets:
      - db_password
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  backend:
    image : velmrok/chess-backend:v2 
    container_name: chess_backend_production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORTS=5062
      - ConnectionStrings__Host=db
      - ConnectionStrings__Database=${POSTGRES_DB}
      - ConnectionStrings__Username=${POSTGRES_USER}
      - Storage__Provider=Local
      - Storage__AccountId=${CF_ACCOUNT_ID}
      - Storage__BucketName=${CF_BUCKET_NAME}
      - Storage__PublicBaseUrl=${CF_PUBLIC_URL}
      - Keycloak__Authority=${APP_BASE_URL}/realms/chess
    depends_on:
      db :
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - frontend-net
      - db-net
    secrets:
      - db_password
      - cf_access_key
      - cf_secret_key
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5062/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  frontend:
    # build:
    #   context: ./frontend
    #   target: production
    #   args:
    #     VITE_KEYCLOAK_AUTHORITY: "${APP_BASE_URL}/realms/chess/"
    #     VITE_KEYCLOAK_REDIRECT_URI: "${APP_BASE_URL}/auth/callback/"
    #     VITE_KEYCLOAK_POST_LOGOUT_URI: "${APP_BASE_URL}/"
    image: velmrok/chess-frontend:v1
    container_name: chess_frontend_production
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - frontend-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M


  redis:
    image: redis:7-alpine
    container_name: chess_redis_production
    volumes:
      - redis_data_production:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: chess_keycloak_production
    command: start --import-realm
    volumes:
    - ./.keycloak-export:/opt/keycloak/data/import:ro
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_PROXY_HEADERS: xforwarded 
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      APP_BASE_URL: ${APP_BASE_URL}
    depends_on:
      keycloak-db:
          condition: service_healthy
    networks:
      - keycloak-net
      - frontend-net
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  keycloak-db:
    container_name: chess_keycloak_db_production
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak_db_data_production:/var/lib/postgresql/data
    networks:
      - keycloak-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER} -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  local-chess-engine:
    image: velmrok/chess-engine:v1 #./local.Chess.Engine
    container_name: local_chess_engine
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - backend-net
    environment:
      - DEPTH=5
      - QDEPTH=15
      - QUANTIZED=--quantized
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 1G
        reservations:
          cpus: "1.0"
          memory: 256M

volumes:
  redis_data_production:
  postgres_data_production:
  data_protection_keys:
  keycloak_db_data_production:
networks:
  frontend-net:
  backend-net:
  db-net:
    internal: true
  keycloak-net:
    internal: true

